import { jsPDF } from 'jspdf';

export function exportClinicalNotePDF(clinicalNote, personalStatement) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let y = 20;

  doc.setFillColor(13, 148, 136);
  doc.rect(0, 0, pageWidth, 45, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('MindCanvas', margin, y + 10);

  doc.setFontSize(10);
  doc.text('Clinical Art Therapy Assessment', margin, y + 20);

  doc.setTextColor(200, 240, 230);
  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - margin - 60, y + 20);

  y = 55;

  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Patient Expression', margin, y);
  y += 8;

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const stmtLines = doc.splitTextToSize(`"${personalStatement || 'N/A'}"`, contentWidth);
  doc.text(stmtLines, margin, y);
  y += stmtLines.length * 6 + 12;

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  const sections = [
    { label: 'S — Subjective', content: clinicalNote.S || clinicalNote.subjective },
    { label: 'O — Objective', content: clinicalNote.O || clinicalNote.objective },
    { label: 'A — Assessment', content: clinicalNote.A || clinicalNote.assessment },
    { label: 'P — Plan', content: clinicalNote.P || clinicalNote.plan },
  ];

  sections.forEach(({ label, content }) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 41);
    doc.text(label, margin, y);
    y += 7;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(80, 80, 80);
    const lines = doc.splitTextToSize(content || 'N/A', contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5.5 + 10;

    if (y > 260) {
      doc.addPage();
      y = 20;
    }
  });

  doc.setFontSize(7);
  doc.setTextColor(170, 170, 170);
  doc.text(
    'DISCLAIMER: Generated by MindCanvas AI-assisted art therapy screening. Not a medical diagnosis. Not HIPAA compliant.',
    margin,
    285
  );

  doc.save('mindcanvas-clinical-note.pdf');
}

export function exportInsuranceFormPDF(formData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let y = 20;

  doc.setFillColor(13, 148, 136);
  doc.rect(0, 0, pageWidth, 45, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('Mental Health Pre-Authorization', margin, y + 10);

  doc.setFontSize(9);
  doc.text('MindCanvas — Insurance Form + Reclaimant', margin, y + 20);

  doc.setTextColor(200, 240, 230);
  doc.setFontSize(8);
  doc.text(`Date: ${new Date().toLocaleString()}`, pageWidth - margin - 50, y + 20);

  y = 55;

  const fields = [
    { label: 'Chief Complaint', value: formData.chiefComplaint },
    { label: 'Symptom Duration', value: formData.symptomDuration },
    { label: 'Functional Impairment', value: formData.functionalImpairment },
    { label: 'Diagnosis Category', value: formData.diagnosisCategory },
    { label: 'Requested Service', value: formData.requestedService },
    { label: 'Patient Name', value: formData.patientName || 'N/A' },
    { label: 'Date of Birth', value: formData.dob || 'N/A' },
    { label: 'Insurance ID', value: formData.insuranceId || 'N/A' },
  ];

  fields.forEach(({ label, value }) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 41);
    doc.text(label, margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(80, 80, 80);
    const lines = doc.splitTextToSize(value || 'N/A', contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 5.5 + 10;
  });

  doc.setFontSize(7);
  doc.setTextColor(170, 170, 170);
  doc.text(
    'DEMO ONLY — Not a real insurance submission. Generated by MindCanvas.',
    margin,
    285
  );

  doc.save('mindcanvas-insurance-form.pdf');
}
